version: '3'
services:
  express-service:
    build:
      context: ./express-service
    ports:
      - '3200:3200'
    depends_on:
      - python

  python:
    build:
      context: ./python
    command: python python_script.py